"""baseline

Revision ID: c5772edd5b54
Revises: 
Create Date: 2026-05-17 10:48:08.797423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5772edd5b54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_lookup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_raw', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_attempted', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_raw')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('company_normalized', sa.String(), nullable=True),
    sa.Column('title_normalized', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('apply_url_normalized', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('profile_hash', sa.String(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_job_source_external_id')
    )
    op.create_index('idx_apply_url_normalized', 'job_postings', ['apply_url_normalized'], unique=False)
    op.create_index('idx_company_title_dedup', 'job_postings', ['company_normalized', 'title_normalized', 'found_at'], unique=False)
    op.create_table('run_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('sources_polled', sa.JSON(), nullable=True),
    sa.Column('postings_found', sa.Integer(), nullable=False),
    sa.Column('postings_new', sa.Integer(), nullable=False),
    sa.Column('postings_scored', sa.Integer(), nullable=False),
    sa.Column('alerts_sent', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('profile_hash', sa.String(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('twilio_sid', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('run_log')
    op.drop_index('idx_company_title_dedup', table_name='job_postings')
    op.drop_index('idx_apply_url_normalized', table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_table('company_lookup')
    # ### end Alembic commands ###
